<?php
$configModel = Mage::getModel('jump/config');

//$config = $configModel->getConfig();
//$config['features'] = array('Engage');
$configModel = array_merge(Mage::getStoreConfig('jump/engage_settings'), Mage::getStoreConfig('jump/capture_settings'));
$configModel['features'] = array('Engage', 'Capture');
$jump = janrain\Jump::getInstance($configModel);

// JavaScript Headers

echo $jump->raw_render();
?>
