<?php
require_once(Mage::getBaseDir('lib') . '/janrain/plex/RenderableInterface.php');
require_once(Mage::getBaseDir('lib') . '/janrain/jump/ConfigInterface.php');
require_once(Mage::getBaseDir('lib') . '/janrain/jump/CaptureConfigInterface.php');
require_once(Mage::getBaseDir('lib') . '/janrain/jump/CaptureConfig.php');
require_once(Mage::getBaseDir('lib') . '/janrain/jump/Capture.php');

$configModel = Mage::getModel('janrain_jump/config');

$config = $configModel->getConfig();

$captureConfig = new janrain\jump\CaptureConfig($config);

$capture = new janrain\jump\Capture($captureConfig);

echo $capture->getHtml();