<?php
require Mage::getBaseDir('lib') . '/janrain/PsrAutoloader.php';

$configModel = Mage::getModel('jump/config');

// $config = $configModel->getConfig();

 $captureConfig = new janrain\plex\capture\CaptureConfig($configModel->getConfig());

 $capture = new janrain\plex\capture\Capture($captureConfig);

 echo $capture->getHtml();

echo '<hr />';

$test = $configModel->getTestConfig();

echo 'Test config value: ' . $test;

echo "<hr />";
